#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER asm3 WITH PASSWORD 'asm3';
CREATE DATABASE asm;
GRANT ALL PRIVILEGES ON DATABASE asm TO asm3;
EOSQL

# Connect to the asm database and grant schema privileges
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "asm" <<-EOSQL
GRANT ALL ON SCHEMA public TO asm3;
GRANT CREATE ON SCHEMA public TO asm3;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO asm3;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO asm3;
EOSQL
