services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/docker/postgres/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - asm3_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  asm3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${ASM3_PORT:-8090}:5000"
    environment:
      - ASM3_CONF=/etc/asm3.conf
      # Application URLs
      - ASM3_BASE_URL=${ASM3_BASE_URL}
      - ASM3_SERVICE_URL=${ASM3_SERVICE_URL}
      # SMTP Configuration
      - ASM3_ADMIN_EMAIL=${ASM3_ADMIN_EMAIL}
      - ASM3_FROM_ADDRESS=${ASM3_FROM_ADDRESS}
      - ASM3_SMTP_HOST=${ASM3_SMTP_HOST}
      - ASM3_SMTP_PORT=${ASM3_SMTP_PORT}
      - ASM3_SMTP_USERNAME=${ASM3_SMTP_USERNAME}
      - ASM3_SMTP_PASSWORD=${ASM3_SMTP_PASSWORD}
      - ASM3_SMTP_TLS=${ASM3_SMTP_TLS:-true}
      - ASM3_USE_SENDMAIL=${ASM3_USE_SENDMAIL:-false}
    volumes:
      - ./asm3.conf:/app/asm3.conf:ro
      - asm3_media:/var/lib/asm3/media
      - asm3_cache:/tmp/asm_disk_cache
      # Mount source code for live development - changes reflected immediately!
      - ./src:/app/src:ro
      # Mount static files for live updates
      - ./src/static:/app/src/static
      # Mount media templates for live updates
      - ./src/media:/app/src/media
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - asm3_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - asm3_network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  # Optional: Memcached for session caching
  memcached:
    image: memcached:1.6-alpine
    restart: unless-stopped
    ports:
      - "${MEMCACHED_PORT:-11212}:11211"
    command: memcached -m 64
    networks:
      - asm3_network

  # Cron service for daily tasks
  asm3_cron:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ASM3_CONF=/etc/asm3.conf
      # Application URLs
      - ASM3_BASE_URL=${ASM3_BASE_URL}
      - ASM3_SERVICE_URL=${ASM3_SERVICE_URL}
      # SMTP Configuration for cron tasks
      - ASM3_ADMIN_EMAIL=${ASM3_ADMIN_EMAIL}
      - ASM3_FROM_ADDRESS=${ASM3_FROM_ADDRESS}
      - ASM3_SMTP_HOST=${ASM3_SMTP_HOST}
      - ASM3_SMTP_PORT=${ASM3_SMTP_PORT}
      - ASM3_SMTP_USERNAME=${ASM3_SMTP_USERNAME}
      - ASM3_SMTP_PASSWORD=${ASM3_SMTP_PASSWORD}
      - ASM3_SMTP_TLS=${ASM3_SMTP_TLS:-true}
      - ASM3_USE_SENDMAIL=${ASM3_USE_SENDMAIL:-false}
    volumes:
      - ./asm3.conf:/app/asm3.conf:ro
      - asm3_media:/var/lib/asm3/media
      # Mount source code for live development
      - ./src:/app/src:ro
    depends_on:
      - asm3
      - postgres
    networks:
      - asm3_network
    command: >
      sh -c "
        while true; do
          sleep 3600;
          echo 'Running daily ASM3 maintenance tasks...';
          cd /app/src && python3 cron.py all;
        done
      "

volumes:
  postgres_data:
    driver: local
  asm3_media:
    driver: local
  asm3_cache:
    driver: local
  # redis_data:
  #   driver: local

networks:
  asm3_network:
    driver: bridge